baseurl : "http://praty.live/"
title : ":(){ :|:& };:"
theme: "anubis"
paginate: 10
enableRobotsTXT: true
summaryLength: 40

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0
  - identifier: github
    name: Github
    title: Github
    url: https://github.com/pranair/
    weight: 0



params:
  author: "Pratyush Nair"
  description: ""
  images:
    - images/og-featured.png # relative path to "static" directory
  customCSS:
    - css/my.css # relative path to "assets" directory (don't use main.css filename)
  customJS:
    - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: false
  style: light-without-switcher
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  webmentions:
    login: hugo-theme-anubis
    pingback: true

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
